# Generated by Django 2.2.13 on 2020-10-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_flatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='price_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='price_min',
            field=models.IntegerField(null=True),
        ),
    ]
