# Generated by Django 2.2.13 on 2020-10-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201011_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpage',
            name='token',
        ),
        migrations.AddField(
            model_name='flatpage',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
