# Generated by Django 2.2.13 on 2020-10-11 20:03

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201011_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='flats',
            field=wagtail.core.fields.StreamField([('f_flats', wagtail.core.blocks.StructBlock([('flat', wagtail.core.blocks.PageChooserBlock(help_text='Wohneinheit im Gebäude', required=False))], icon='fa-info'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='available',
            field=models.BooleanField(),
        ),
    ]
