# Generated by Django 2.2.13 on 2020-10-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20201011_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
