# Generated by Django 2.2.13 on 2020-10-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20201014_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='buy_or_rent',
            field=models.CharField(choices=[('RE', 'Miete'), ('BU', 'Kauf')], default='RE', max_length=4, verbose_name='Mieten oder Kaufen?'),
        ),
    ]
